<!-- firstpage.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="firstpage.css">
  <title>Your Brand</title>

</head>
<body >


    <header>
        <div class="left-nav">
          <img id="brand-logo" src="images/logo.png" alt="Brand Logo">
          <a href="#">Team Info</a>
          <a href="secondpage.html">Fixtures & Results</a>
          <a href="thirdpage.html">News</a>
          <a href="#">Tickets</a>
          <a href="#">Shop</a>
          <a href="#">About Us</a>
        </div>
    
        <div class="right-nav">
          <a href="#">Media</a>
          <a href="#">Fans</a>
          <a href="#">More</a>
    
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-search" viewBox="0 0 16 16">
              <path
                  d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"></path>
          </svg>
    
          <i class="material-icons">person_outline</i>
    
          <a href="#">Sign in</a>
        </div>
      </header>


      <section class="main-section">
    
      <div class="image-container-one">
        <img src="images/image-one.jpg" alt="Nature">
        <div class="text-block-image-one">
          <h1>THE 26’TH MARCH MATCH BETWEEN<br> BANGLADESH  & PALESTINE</h1>
          <p>Teams are warming up this season with the most anticipated <br> match that has been awaited for so long.....</p>
          <div class="countdown">
            <br>
          <h1>  <span>30</span> Days | <span>11</span> Hours | <span>16</span> Minutes <h1>
          </div>
        </div>
      </div>
     
      <section>
        <div class="header-one">

            <div class="header-one-exented">
                <h1 class="text-one">Fixtures</h1>
                <div class="align-item"></div>
                <p class="text-two">See Calender</p>

            </div>

            <div class="header-one-exented">

                <h1 class="text-one">Club Rankings</h1>
                <div class="align-item"></div>
                <p class="text-two">See More</p>

            </div>


        </div>
      </section>

      



<section class="Fixtures-Club-Rankings">
    <div class="Score-board-table">
        <!---first container-->

        <div class="first-score-board">
            <h2 class="date">Sat, Sep 25 19:00 Kyiv</h2>
            <p>Premier league</p>
            <div class="image-score">
                <img class="image-logo" src="images/chelsea.png">
                <h1 class="score"> 3 - 4</h1>
                <img class="image-logo" src="images/brinton.png">
            </div>
            <div class="team-name">
                <h1 class="team-name-extended">CHELSEA</h1>
                <h1 class="team-name-extended">BRIGHTON</h1>
            </div>

            <div class="news-name">
                <p>Donetsk</p>
                <p>Odesa</p>
            </div>

            <div class="News-Highlight">
                <h1>News</h1>
                <h1>Highlighst</h1>
            </div>

        </div>

        <!---first container-->

        <div class="first-score-board-new">
            <h2 class="date">Sat, Sep 25 19:00 Kyiv</h2>
            <p>Premier league</p>
            <div class="image-score">
                <img class="image-logo" src="images/chelsea.png">
                <h1 class="score"> 3 - 4</h1>
                <img class="image-logo" src="images/brinton.png">
            </div>
            <div class="team-name">
                <h1 class="team-name-extended">CHELSEA</h1>
                <h1 class="team-name-extended">BRIGHTON</h1>
            </div>

            <div class="news-name">
                <p>Donetsk</p>
                <p>Odesa</p>
            </div>

            <div class="News-Highlight">
                <h1>News</h1>
                <h1>Highlighst</h1>
            </div>

        </div >

        <div class="table-pro">
          <table class="main-table">
            <tr class="text-of-table">
              <th></th>
                <th>Club</th>
                <th></th>
                <th>GP</th>
                <th>W</th>
                <th>D</th>
                <th>L</th>
                <th>F</th>
                <th>A</th>
                <th>GD</th>
            </tr>
            <tr class="first-tr">
              <td>1</td>
              <td><img class="table-image" src="images/city.png"></td>
                <td>Manchester City</td>
                <td>38</td>
                <td>29</td>
                <td>6</td>
                <td>3</td>
                <td>99</td>
                <td>26</td>
                <td>73</td>
            </tr>
            <div>
              <div class="White-line"></div>
           </div>
           
            <tr class="first-tr">
              <td>2</td>
              <td><img class="table-image" src="images/liverpool.png"></td>
                <td>Liverpool</td>
                <td>38</td>
                <td>28</td>
                <td>8</td>
                <td>2</td>
                <td>94</td>
                <td>26</td>
                <td>68</td>
            </tr>
            <tr class="first-tr">
              <td>3</td>
              <td><img class="table-image" src="images/chelsea.png"></td>
                <td>Chelsea</td>
                <td>38</td>
                <td>21</td>
                <td>11</td>
                <td>6</td>
                <td>76</td>
                <td>33</td>
                <td>43</td>
            </tr>
            <tr class="first-tr">
              <td>4</td>
              <td><img class="table-image" src="images/tottem.png"></td>
                <td>Tottenham Hotspur</td>
                <td>38</td>
                <td>22</td>
                <td>5</td>
                <td>11</td>
                <td>69</td>
                <td>40</td>
                <td>29</td>
            </tr>
            <tr class="first-tr">
              <td>5</td>
              <td><img class="table-image" src="images/arsenal.png"></td>
                <td>Arsenal</td>
                <td>38</td>
                <td>22</td>
                <td>3</td>
                <td>13</td>
                <td>61</td>
                <td>48</td>
                <td>13</td>
            </tr>
            <tr class="first-tr">
              <td>6</td>
              <td><img class="table-image" src="images/united.png"></td>
                <td>Manchester United</td>
                <td>38</td>
                <td>16</td>
                <td>10</td>
                <td>12</td>
                <td>57</td>
                <td>57</td>
                <td>0</td>
            </tr>
  
          </table>
  
  
  
         
        </div>
        



    </div>


</section>

<section>
      <div class="header-two-exented">
          <h1 class="text-one">Editor Picks</h1>
          <div class="align-item"></div>
          <p class="text-two" >More News</p>

      </div>

    </section>


    <section class="Editor-picks-div">
      <div class="first-image">
        <img class="Editor-picks-image-first" src="images/editorpicksone.jpg" >
        <div class="Editor-picks-extended-text">
          <p class="eiditor-picks-name">
            Rangnick suffers first defeat as<br>Wolves win
          </p>
          <div class="football-hours-two">
            <p class="football-text">Football</p>
            <p class="hours" >6 hours ago</p>
          </div>
        </div>
      </div>
    
      <div class="Editor-picks-others">
        <div class="Editor-picks-others-extend">
          <img src="images/editortwo.png">
          <div class="Editor-picks-others-extend-text">
            <h1>Scamacca opens West Ham account</h1>
            <div class="football-hours-two">
              <p class="football-text">Premier league</p>
              <p class="hours">6 hours ago</p>
            </div>
          </div>
        </div>
    
        <div class="Editor-picks-others-extend">
          <img src="images/editorthree.png">
          <div class="Editor-picks-others-extend-text">
            <h1>Adaptable approach: Boks not reverting to a rigid
             plan a in decider</h1>
            <div class="football-hours-two">
              <p class="football-text">Springboks</p>
              <p class="hours">6 hours ago</p>
            </div>
          </div>
        </div>
    
        <div class="Editor-picks-others-extend">
          <img src="images/editorfour.jpg">
          <div class="Editor-picks-others-extend-text">
            <h1>Training Day No. 01 These Guys Debut Today</h1>
            <div class="football-hours-two">
              <p class="football-text">PSL</p>
              <p class="hours">6 hours ago</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    
      
   <!-- new block -->
   <div class="container">
    <div class="blue-color-text-container">
        <div class="text-content">
            <h1 class="heading-text">Buy Season Tickets For The Second Part of The Season</h1>
            <a class="button-class" href="">Buy Season Tickets</a>
        </div>
    </div>
    <div class="stadium-image-container">
        <img src="images/stadium.jpg" alt="">
    </div>
</div>

<section>
  <div class="header-two-exented">
      <h1 class="text-one">Competitions</h1>
    
  </div>

</section>
<section class="Premier-section">

<div class="profile">
  <img class="profile-picture" src="images/uefa.jpg">
  <p class="name">
    UEFA Champions League.
  </p>
  <div class="mutual-friends-row">
    <p class="mutual-friends">
      Competition ends 5 July

    </p>
  </div>

</div>


<div class="profile">
  <img class="profile-picture" src="images/bundesliga.png">
  <p class="name">
    Bundesliga
  </p>
  <div class="mutual-friends-row">
    <p class="mutual-friends">
      Competition ends 5 July

    </p>
  </div>

</div>

<div class="profile">
  <img class="profile-picture" src="images/lalilag_two.jpg">
  <p class="name">
    LALIGA 202
  </p>
  <div class="mutual-friends-row">
    <p class="mutual-friends">
      Competition ends 5 July

    </p>
  </div>

</div>

<div class="profile">
  <img class="profile-picture" src="images/premier.jpg">
  <p class="name">
    Win your Tickets fot UEFA Champions League.
  </p>
  <div class="mutual-friends-row">
    <p class="mutual-friends">
      Competition ends 5 July

    </p>
  </div>

</div>

</section>

<section>
  <div class="header-two-exented">
      <h1 class="text-one">Watch videos</h1>
      <div class="align-item"></div>
      <p class="text-two" >More</p>

  </div>
</section>
<section class="passing-football-section">
  <div class="passing-football">
    
    <div class="passing">
      <img class="passing-image" src="images/passing.jpg" alt="Passing Image">
    </div>

  <div class="passing-text">
    <h1 class="football-text-extends">‘Got a bit cocky’: Tszyu<br> 
      returns to scene of <br>
       ‘embarrassment’ that still <br>drives him</h1>
       <div class="football-hours">
    <p class="football-text">Football</p>
    <p class="hours" >6 hours ago</p>
       </div>
  </div>
</div>
</section>

<section class="Premier-section">

  <div class="profile">
    <img class="profile-picture" src="images/manushone.jpg">
    <p class="name">
      Venus Williams to make singles comeback in <br>Toronto
    </p>
    <div class="football-hours-two">
      <p class="football-text">FIFA</p>
      <p class="hours" >6 hours ago</p>
         </div>
  
  </div>
  
  
  <div class="profile">
    <img class="profile-picture" src="images/stadium_two.jpg">
    <p class="name">
      Lewis Hamilton and Mercedes AMG Petronas <br>take top spot
    </p>
    <div class="football-hours-two">
      <p class="football-text">Premier League</p>
      <p class="hours" >6 hours ago</p>
         </div>
  
  </div>
  
  <div class="profile">
    <img class="profile-picture" src="images/manus_two.png">
    <p class="name">
      Hideki Matsuyama of Japan speaks with his <br>caddie on the 10th green
    </p>
    <div class="football-hours-two">
      <p class="football-text">US PGA Tour</p>
      <p class="hours" >6 hours ago</p>
         </div>
  
  </div>
  
  <div class="profile">
    <img class="profile-picture" src="images/manush_three.png">
    <p class="name">
      PSL and Soweto giants Strengthen Their <br>Partnership
    </p>
    <div class="football-hours-two">
      <p class="football-text">Premier League</p>
      <p class="hours" >6 hours ago</p>
         </div>
  
  </div>
  
  </section>
  <!-- new block 2 -->
  <section class="join-bff">
    <div class="join-bff-container">
        <img src="images/2image.jpg" alt="">
        <div class="join-bff-text">
            <h1 class="heading-text">Join The BFF Fan Club And <br>
                Share Your Thoughts
            </h1>
            <a class="button-class" href="">Register</a>
        </div>
    </div>

</section>

  <section class="brand-image-section">

  <div class="brand-image">
    <div class="brand-image-exented">
      <img class="brand-logo-image" src="images/starsports.png">
    </div>
    <div class="brand-image-exented">
      <img class="brand-logo-image" src="images/aamra.png">
    </div>
    <div> 
    <img class="brand-logo-image" src="images/fila.png">
    </div>
    <div>
      <img class="brand-logo-image" src="images/unicef.png">
    </div>
    <div>
      <img class="brand-logo-image" src="images/biman.png">

    </div>
  </div>


</section>
</seciton>
<!-- footer section 0d242f -->
<footer class="footer-class">
  <div class="footer-container">
      <!-- logo container -->
      <div class="logo-container">
          <div class="logo-element">
              <img src="images/bafufe (1).png" alt="">
              <h1>
                  bangladesh football <br> federation
              </h1>
              <p>BFF HOUSE, 14/B, Toyenbee Circular
                  <br>
                  Road, Motijheel C/A, Dhaka-1000, Bangladesh.
              </p>
              <p>
                  +88-02-223354232, 223350331 <br>
                  mailto: info@bff.com.bd
              </p>
          </div>
          <div class="vertical-line"></div>
      </div>
      <!-- sports-container -->
      <div class="sporst-container">
          <h1>Sports</h1>
          <p>Terms</p>
          <p>Coaching</p>
          <p>Refereeing</p>
          <p>Document Library</p>
          <p>Find Football</p>
      </div>
      <!-- access-container -->
      <div class="access-container">
          <h1>Access</h1>
          <p>TV Guide</p>
          <p>Watch Live</p>
          <p>Podcasts</p>
          <p>iOS App</p>
          <p>Android App</p>
      </div>
      <!-- about container -->
      <div class="about-container">
          <h1>About</h1>
          <p>About US</p>
          <p>Careers</p>
      </div>
     
  </div>
   <!-- footer down side -->
   <div class="footer-second-color">
      <p>&copy; 2024 BANGLADESH FOOTBALL FEDERATION. All rights reserved </p>
      <div class="social-logo-container">
          <img src="images/facebook.png" alt="">
          <img src="images/twitter.png" alt="">
          <img src="images/youtube.png" alt="">
          <img src="images/insta.png" alt="">
          <img src="images/linkeid.png" alt="">
      </div>
  </div>

</footer>


    
    
    



</body>
</html>
